### ISSUE TITLE
Add support for Localize full replace

### ISSUE THREAD

**Issue by xipasduarte** [26B/i18n-midoru#34]
When uploading a template file to Localize.biz, there is the option to remove any non existent key. Add this setting to the available options on the JSON config file and do destructive updates.

*Note:* How could we make this safer? Maybe have a backup feature to download the contents before?

**Comment by goncaloasimoes** [comment]
Regarding the safety aspect, we can add a `backup` option to the config (default is false) where it downloads the contents before doing a destructive update and places them in a backup folder like `.i18n-midoru-backup` in the root where the json/lock is. Everytime we do a destructive update, we overwrite the backups in that folder, meaning we would always keep the previous version of the content.

As an extension of this idea, we could also have the `backup` option be a number which means the amount of backups we keep per project (config entry). This way, we would backup the contents until we reach the given number and after that remove the oldest one for the new content. This would give the user more safety since it might not be apparent when the damage was done and they might have already done various destructive updates, losing the translations.

**Comment by xipasduarte** [comment]
It seems to complex for what is needed. Given that Localize offers the other option, we don't need anything. Perhaps a double check question, although this would need to be cancelled when using the CLI version.
